Adds Custom Code for Compare
aws-controllers-k8s/applicationautoscaling-controller pull request #12
Opened 2021-05-26 09:49 UTC by mbaijal

The ScalableTarget Resource has two fields which do not work with the existing ACK CompareResource functionality. This PR fixes this issue by adding these two fields to the ignore list for compare and then adding custom logic. 

More details discussed in [Issue #796](https://github.com/aws-controllers-k8s/community/issues/796)

### Testing
- I tested that the logs were as expected at each step - before any changes; after removing the compare logic entirely; after adding the custom compare function with no changes and finally the custom compare with the new checks. 
- I also checked the logs after manually testing with the suspendedState field added to the spec.

2021-05-26 21:03 UTC, surajkota requested changes

2021-05-27 00:59 UTC, RedbackThomson commented
/ok-to-test

2021-05-27 01:18 UTC, RedbackThomson commented
/ok-to-test

2021-05-27 08:05 UTC, mbaijal commented on pkg/resource/scalable_target/custom_api.go
> +func customCompare(
done

2021-05-27 08:49 UTC, mbaijal commented on pkg/resource/scalable_target/custom_api.go
> +	if a.ko.Spec.SuspendedState != nil {
Most of these resources do not support updates, so not really an issue but I agree this approach of setting defaults is a better one, fixed for suspendedState. Left RoleARN as is.

2021-05-27 21:01 UTC, surajkota approved these changes
/approve
/lgtm

2021-05-27 21:14 UTC, merged

2021-06-02 13:41 UTC, jaypipes commented
@mbaijal @surajkota I would recommend this PR be reverted. The code is setting these values properly: https://github.com/aws-controllers-k8s/applicationautoscaling-controller/blob/d047c6153a1fc116c7b85d85dc7652e11c8491f1/pkg/resource/scalable_target/sdk.go#L85-L114

The root cause of the issue you are seeing has nothing to do with the Delta/Compare code and everything to do with this line in the code-generator template for manager.go:

https://github.com/aws-controllers-k8s/code-generator/blob/main/templates/pkg/resource/manager.go.tpl#L77

That needs to pass `observed` to `onError` instead of `r`. That is the reason that you are seeing the desired and observed resource not seem to change values when sdkFind() returns.

/cc @A-Hilaly